import { onlyUnique } from "./onlyUnique"

export const glossary = [
{id: `394DFA83`, jp: `水星`, en: `Mercury`, key: `mercury`, category: `mercury`, url: `https://astro-dic.jp/mercury/`, url_en: ``},
{id: `68AB734A`, jp: `金星`, en: `Venus`, key: `venus`, category: `venus`, url: `https://astro-dic.jp/venus/`, url_en: ``},
{id: `74C63F47`, jp: `火星`, en: `Mars`, key: `mars`, category: `mars`, url: `https://astro-dic.jp/mars/`, url_en: ``},
{id: `EC3B122D`, jp: `木星`, en: `Jupiter`, key: `jupiter`, category: `jupiter`, url: `https://astro-dic.jp/jupiter/`, url_en: ``},
{id: `BC34E5F2`, jp: `土星`, en: `Saturn`, key: `saturn`, category: `saturn`, url: `https://astro-dic.jp/saturn/`, url_en: ``},
{id: `826344C4`, jp: `天王星`, en: `Uranus`, key: `uranus`, category: `uranus`, url: `https://astro-dic.jp/uranus/`, url_en: ``},
{id: `D395D495`, jp: `海王星`, en: `Neptune`, key: `neptune`, category: `neptune`, url: `https://astro-dic.jp/neptune/`, url_en: ``},
{id: `41B846B4`, jp: `地球型惑星`, en: `Terrestrial Planet`, key: `terrestrial_planet`, category: `planets`, url: `https://astro-dic.jp/terrestrial-planet/`, url_en: ``},
{id: `020D4771`, jp: `木星型惑星`, en: `Jovian Planets`, key: `jovian_planets`, category: `planets`, url: `https://astro-dic.jp/jovian-planets/`, url_en: ``},
{id: `04238F8F`, jp: `巨大ガス惑星`, en: `Gas Giant`, key: `gas_giant`, category: `planets`, url: `https://astro-dic.jp/gas-giant-planet/`, url_en: ``},
{id: `E6528E1C`, jp: `氷惑星`, en: `Icy Planet`, key: `icy_planet`, category: `planets`, url: `https://astro-dic.jp/icy-planet/`, url_en: ``},
{id: `81A596B6`, jp: `水星`, en: `Mercury`, key: `mercury`, category: `planets`, url: `https://astro-dic.jp/mercury/`, url_en: ``},
{id: `1D36EDDB`, jp: `金星`, en: `Venus`, key: `venus`, category: `planets`, url: `https://astro-dic.jp/venus/`, url_en: ``},
{id: `29EDB5D5`, jp: `火星`, en: `Mars`, key: `mars`, category: `planets`, url: `https://astro-dic.jp/mars/`, url_en: ``},
{id: `C36176E7`, jp: `木星`, en: `Jupiter`, key: `jupiter`, category: `planets`, url: `https://astro-dic.jp/jupiter/`, url_en: ``},
{id: `F03F277F`, jp: `土星`, en: `Saturn`, key: `saturn`, category: `planets`, url: `https://astro-dic.jp/saturn/`, url_en: ``},
{id: `1391E201`, jp: `天王星`, en: `Uranus`, key: `uranus`, category: `planets`, url: `https://astro-dic.jp/uranus/`, url_en: ``},
{id: `89154B54`, jp: `海王星`, en: `Neptune`, key: `neptune`, category: `planets`, url: `https://astro-dic.jp/neptune/`, url_en: ``},
{id: `5D49D01C`, jp: `水星の磁場`, en: `Mercury Magnetic Fields`, key: `mercury_magnetic_fields`, category: `mercury`, url: `https://astro-dic.jp/planetary-magnetic-fields/`, url_en: ``},
{id: `E168AF56`, jp: `木星の磁場`, en: `Jupiter Magnetic Fields`, key: `jupiter_magnetic_fields`, category: `jupiter`, url: `https://astro-dic.jp/planetary-magnetic-fields/`, url_en: ``},
{id: `9DDCF41D`, jp: `土星の磁場`, en: `Saturn Magnetic Fields`, key: `saturn_magnetic_fields`, category: `saturn`, url: `https://astro-dic.jp/planetary-magnetic-fields/`, url_en: ``},
{id: `AF998752`, jp: `天王星の磁場`, en: `Uranus Magnetic Fields`, key: `uranus_magnetic_fields`, category: `uranus`, url: `https://astro-dic.jp/planetary-magnetic-fields/`, url_en: ``},
{id: `4CDE0842`, jp: `大赤斑`, en: `Great Red Spot`, key: `great_red_spot`, category: `jupiter`, url: `https://astro-dic.jp/great-red-spot/`, url_en: ``},
{id: `AD1B8F5E`, jp: `カッシーニの間隙 (土星)`, en: `Cassini Division`, key: `cassini_division`, category: `saturn`, url: `https://astro-dic.jp/cassini-division/`, url_en: ``},
{id: `A5E799FA`, jp: `月`, en: `Moon`, key: `moon`, category: `moon_earth`, url: `https://astro-dic.jp/moon/`, url_en: ``},
{id: `494A8741`, jp: `月面の海`, en: `Mare`, key: `mare`, category: `moon_earth`, url: `https://astro-dic.jp/mare/`, url_en: ``},
{id: `721D0137`, jp: `月の高地`, en: `Highland Of Moon`, key: `highland_of_moon`, category: `moon_earth`, url: `https://astro-dic.jp/highland-of-moon/`, url_en: ``},
{id: `E88DBE31`, jp: `フォボス (衛星)`, en: `Phobos`, key: `phobos`, category: `mars`, url: `https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A9%E3%83%9C%E3%82%B9_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `2CB11DEF`, jp: `ダイモス (衛星)`, en: `Deimos`, key: `deimos`, category: `mars`, url: `https://ja.wikipedia.org/wiki/%E3%83%80%E3%82%A4%E3%83%A2%E3%82%B9_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `2A646177`, jp: `イオ (衛星)`, en: `Io`, key: `io`, category: `jupiter`, url: `https://astro-dic.jp/io/`, url_en: ``},
{id: `4C85A5D3`, jp: `エウロパ (衛星)`, en: `Europa`, key: `europa`, category: `jupiter`, url: `https://astro-dic.jp/europa/`, url_en: ``},
{id: `545B8216`, jp: `ガニメデ (衛星)`, en: `Ganymede`, key: `ganymede`, category: `jupiter`, url: `https://astro-dic.jp/ganymede/`, url_en: ``},
{id: `8ACF1E26`, jp: `カリスト (衛星)`, en: `Callisto`, key: `callisto`, category: `jupiter`, url: `https://astro-dic.jp/callisto/`, url_en: ``},
{id: `2A8A070D`, jp: `ガリレオ衛星`, en: `Galilean Satellites`, key: `galilean_satellites`, category: `jupiter`, url: `https://astro-dic.jp/galilean-satellites/`, url_en: ``},
{id: `88D6D1F2`, jp: `アモルファス氷 (ガニメデ)`, en: `Ganymede Amorphous Ice`, key: `ganymede_amorphous_ice`, category: `jupiter`, url: `https://astro-dic.jp/amorphous-ice/`, url_en: ``},
{id: `EF3DFC2A`, jp: `潮汐加熱 (イオ)`, en: `Tidal Heating`, key: `tidal_heating`, category: `jupiter`, url: `https://astro-dic.jp/tidal-heating/`, url_en: ``},
{id: `2EB55993`, jp: `エンセラダス (衛星)`, en: `Enceladus`, key: `enceladus`, category: `saturn`, url: `https://astro-dic.jp/enceladus/`, url_en: ``},
{id: `6E49F722`, jp: `タイタン (衛星)`, en: `Titan`, key: `titan`, category: `saturn`, url: `https://astro-dic.jp/titan/`, url_en: ``},
{id: `4775883C`, jp: `テティス (衛星)`, en: `Tethys`, key: `tethys`, category: `saturn`, url: `https://ja.wikipedia.org/wiki/%E3%83%86%E3%83%86%E3%82%A3%E3%82%B9_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `4418820B`, jp: `ディオネ (衛星)`, en: `Dione`, key: `dione`, category: `saturn`, url: `https://ja.wikipedia.org/wiki/%E3%83%87%E3%82%A3%E3%82%AA%E3%83%8D_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `15B8D012`, jp: `レア (衛星)`, en: `Rhea`, key: `rhea`, category: `saturn`, url: `https://ja.wikipedia.org/wiki/%E3%83%AC%E3%82%A2_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `9896C147`, jp: `イアペトゥス (衛星)`, en: `Iapetus`, key: `iapetus`, category: `saturn`, url: `https://ja.wikipedia.org/wiki/%E3%82%A4%E3%82%A2%E3%83%9A%E3%83%88%E3%82%A5%E3%82%B9_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `0BF37818`, jp: `ミランダ (衛星)`, en: `Miranda`, key: `miranda`, category: `uranus`, url: `https://ja.wikipedia.org/wiki/%E3%83%9F%E3%83%A9%E3%83%B3%E3%83%80_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `5966C95F`, jp: `アリエル (衛星)`, en: `Ariel`, key: `ariel`, category: `uranus`, url: `https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%AA%E3%82%A8%E3%83%AB_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `3DE82F1A`, jp: `ウンブリエル (衛星)`, en: `Umbriel`, key: `umbriel`, category: `uranus`, url: `https://ja.wikipedia.org/wiki/%E3%82%A6%E3%83%B3%E3%83%96%E3%83%AA%E3%82%A8%E3%83%AB`, url_en: ``},
{id: `60DD577B`, jp: `チタニア(衛星)`, en: `Titania`, key: `titania`, category: `uranus`, url: `https://ja.wikipedia.org/wiki/%E3%83%81%E3%82%BF%E3%83%8B%E3%82%A2_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `1B6FD5E8`, jp: `オベロン(衛星)`, en: `Oberon`, key: `oberon`, category: `uranus`, url: `https://ja.wikipedia.org/wiki/%E3%82%AA%E3%83%99%E3%83%AD%E3%83%B3_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `9F55E101`, jp: `ネレイド (衛星)`, en: `Nereid`, key: `nereid`, category: `neptune`, url: `https://ja.wikipedia.org/wiki/%E3%83%8D%E3%83%AC%E3%82%A4%E3%83%89_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `381391ED`, jp: `トリトン (衛星)`, en: `Triton`, key: `triton`, category: `neptune`, url: ``, url_en: ``},
{id: `35A33077`, jp: `羊飼い衛星`, en: `Shepherd Satellite`, key: `shepherd_satellite`, category: `saturn`, url: `https://astro-dic.jp/shepherd-satellite/`, url_en: ``},
{id: `4CCC7F04`, jp: `エンケの間隙`, en: `Encke Gap`, key: `encke_gap`, category: `saturn`, url: `https://astro-dic.jp/encke-gap/`, url_en: ``},
{id: `D911FD3F`, jp: `月`, en: `Moon`, key: `moon`, category: `moons`, url: `https://astro-dic.jp/moon/`, url_en: ``},
{id: `D29D8F52`, jp: `月面の海`, en: `Mare`, key: `mare`, category: `moons`, url: `https://astro-dic.jp/mare/`, url_en: ``},
{id: `E6D63B64`, jp: `月の高地`, en: `Highland Of Moon`, key: `highland_of_moon`, category: `moons`, url: `https://astro-dic.jp/highland-of-moon/`, url_en: ``},
{id: `F2F172DC`, jp: `フォボス (火星)`, en: `Phobos`, key: `phobos`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A9%E3%83%9C%E3%82%B9_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `45131031`, jp: `ダイモス (火星)`, en: `Deimos`, key: `deimos`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%83%80%E3%82%A4%E3%83%A2%E3%82%B9_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `8EEF9781`, jp: `イオ (木星)`, en: `Io`, key: `io`, category: `moons`, url: `https://astro-dic.jp/io/`, url_en: ``},
{id: `CE38A1B3`, jp: `エウロパ (木星)`, en: `Europa`, key: `europa`, category: `moons`, url: `https://astro-dic.jp/europa/`, url_en: ``},
{id: `9698970A`, jp: `ガニメデ (木星)`, en: `Ganymede`, key: `ganymede`, category: `moons`, url: `https://astro-dic.jp/ganymede/`, url_en: ``},
{id: `37723664`, jp: `カリスト (木星)`, en: `Callisto`, key: `callisto`, category: `moons`, url: `https://astro-dic.jp/callisto/`, url_en: ``},
{id: `34ABA46F`, jp: `ガリレオ衛星 (木星)`, en: `Galilean Satellites`, key: `galilean_satellites`, category: `moons`, url: `https://astro-dic.jp/galilean-satellites/`, url_en: ``},
{id: `8F9258B8`, jp: `アモルファス氷 (ガニメデ)`, en: `Ganymede Amorphous Ice`, key: `ganymede_amorphous_ice`, category: `moons`, url: `https://astro-dic.jp/amorphous-ice/`, url_en: ``},
{id: `AA5BD00F`, jp: `潮汐加熱 (イオ)`, en: `Tidal Heating`, key: `tidal_heating`, category: `moons`, url: `https://astro-dic.jp/tidal-heating/`, url_en: ``},
{id: `F091EFF6`, jp: `エンセラダス (木星)`, en: `Enceladus`, key: `enceladus`, category: `moons`, url: `https://astro-dic.jp/enceladus/`, url_en: ``},
{id: `5EF535E5`, jp: `タイタン (土星)`, en: `Titan`, key: `titan`, category: `moons`, url: `https://astro-dic.jp/titan/`, url_en: ``},
{id: `559285B6`, jp: `テティス (土星)`, en: `Tethys`, key: `tethys`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%83%86%E3%83%86%E3%82%A3%E3%82%B9_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `40FF6616`, jp: `ディオネ (土星)`, en: `Dione`, key: `dione`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%83%87%E3%82%A3%E3%82%AA%E3%83%8D_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `B9A32B30`, jp: `レア (土星)`, en: `Rhea`, key: `rhea`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%83%AC%E3%82%A2_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `516BA1F7`, jp: `イアペトゥス (土星)`, en: `Iapetus`, key: `iapetus`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%82%A4%E3%82%A2%E3%83%9A%E3%83%88%E3%82%A5%E3%82%B9_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `638AAF53`, jp: `ミランダ (天王星)`, en: `Miranda`, key: `miranda`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%83%9F%E3%83%A9%E3%83%B3%E3%83%80_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `1332BC27`, jp: `アリエル (天王星)`, en: `Ariel`, key: `ariel`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%AA%E3%82%A8%E3%83%AB_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `37D11F4F`, jp: `ウンブリエル (天王星)`, en: `Umbriel`, key: `umbriel`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%82%A6%E3%83%B3%E3%83%96%E3%83%AA%E3%82%A8%E3%83%AB`, url_en: ``},
{id: `BBAFB2A7`, jp: `チタニア(天王星)`, en: `Titania`, key: `titania`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%83%81%E3%82%BF%E3%83%8B%E3%82%A2_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `EF6DC066`, jp: `オベロン(天王星)`, en: `Oberon`, key: `oberon`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%82%AA%E3%83%99%E3%83%AD%E3%83%B3_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `CF4156A1`, jp: `ネレイド (海王星)`, en: `Nereid`, key: `nereid`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%83%8D%E3%83%AC%E3%82%A4%E3%83%89_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `761DF834`, jp: `トリトン (海王星)`, en: `Triton`, key: `triton`, category: `moons`, url: ``, url_en: ``},
{id: `538E94A2`, jp: `羊飼い衛星`, en: `Shepherd Satellite`, key: `shepherd_satellite`, category: `moons`, url: `https://astro-dic.jp/shepherd-satellite/`, url_en: ``},
{id: `7ABCDAE5`, jp: `エンケの間隙`, en: `Encke Gap`, key: `encke_gap`, category: `moons`, url: `https://astro-dic.jp/encke-gap/`, url_en: ``},
{id: `C26E327C`, jp: `カロン (冥王星)`, en: `Charon`, key: `charon`, category: `moons`, url: `https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%AD%E3%83%B3_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `5D3A4E01`, jp: `準惑星`, en: `Dwarf Planet`, key: `dwarf_planet`, category: `dwarf_planet`, url: `https://astro-dic.jp/dwarf-planet/`, url_en: ``},
{id: `572C1585`, jp: `冥王星`, en: `Pluto`, key: `pluto`, category: `dwarf_planet`, url: `https://astro-dic.jp/pluto/`, url_en: ``},
{id: `4C4BF937`, jp: `カロン (衛星)`, en: `Charon`, key: `charon`, category: `dwarf_planet`, url: `https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%AD%E3%83%B3_(%E8%A1%9B%E6%98%9F)`, url_en: ``},
{id: `68F36963`, jp: `エリス`, en: `Eris`, key: `eris`, category: `dwarf_planet`, url: `https://astro-dic.jp/eris/`, url_en: ``},
{id: `2FE17242`, jp: `ケレス`, en: `Ceres`, key: `ceres`, category: `dwarf_planet`, url: `https://astro-dic.jp/ceres/`, url_en: ``},
{id: `19C6329A`, jp: `小惑星`, en: `Asteroids`, key: `asteroids`, category: `asteroids`, url: `https://astro-dic.jp/asteroids/`, url_en: ``},
{id: `400861C8`, jp: `小惑星帯`, en: `Asteroid Belt`, key: `asteroid_belt`, category: `asteroids`, url: `https://astro-dic.jp/asteroid-belt/`, url_en: ``},
{id: `56E02B6A`, jp: `トロヤ群小惑星`, en: `Trojan Asteroids`, key: `trojan_asteroids`, category: `asteroids`, url: `https://astro-dic.jp/trojan-asteroids/`, url_en: ``},
{id: `29848995`, jp: `地球接近小惑星`, en: `Near Earth Asteroids`, key: `near_earth_asteroids`, category: `asteroids`, url: `https://astro-dic.jp/near-earth-asteroids/`, url_en: ``},
{id: `B6EBF706`, jp: `カークウッドの間隙`, en: `Kirkwood`, key: `kirkwood`, category: `asteroids`, url: `https://astro-dic.jp/kirkwood-gap/`, url_en: ``},
{id: `DD2AE9C7`, jp: `彗星`, en: `Comet`, key: `comet`, category: `comet`, url: `https://astro-dic.jp/comet/`, url_en: ``},
{id: `394F035D`, jp: `彗星のコマ`, en: `Comet Coma`, key: `comet_coma`, category: `comet`, url: `https://astro-dic.jp/coma/`, url_en: ``},
{id: `8C4E7558`, jp: `彗星の尾`, en: `Comet Tail`, key: `comet_tail`, category: `comet`, url: `https://astro-dic.jp/tail/`, url_en: ``},
{id: `E941AAF1`, jp: `ハレー彗星`, en: `Comet Halley`, key: `comet_halley`, category: `comet`, url: `https://astro-dic.jp/comet-halley/`, url_en: ``},
{id: `868006B8`, jp: `ヘール‐ボップ彗星`, en: `Comet Hale-Bopp`, key: `comet_hale-bopp`, category: `comet`, url: `https://astro-dic.jp/hale-bopp/`, url_en: ``},
{id: `64AE6DA7`, jp: `周期彗星`, en: `Periodic Comet`, key: `periodic_comet`, category: `comet`, url: `https://astro-dic.jp/periodic-comet/`, url_en: ``},
{id: `42CA8F4B`, jp: `地球接近天体`, en: `Near Earth Object`, key: `near_earth_object`, category: `comet`, url: `https://astro-dic.jp/near-earth-object/`, url_en: ``},
{id: `CB2C512F`, jp: `太陽系外縁天体`, en: `Trans-Neptunian Object`, key: `trans-neptunian_object`, category: `trans_neptunian`, url: `https://astro-dic.jp/trans-neptunian-object-5/`, url_en: ``},
{id: `A3AFB0B5`, jp: `カイパーベルト`, en: `Kuiper Belt`, key: `kuiper_belt`, category: `trans_neptunian`, url: `https://astro-dic.jp/edgeworth-kuiper-belt-object/`, url_en: ``},
{id: `8215BF32`, jp: `セドナ`, en: `Sedna`, key: `sedna`, category: `trans_neptunian`, url: `https://astro-dic.jp/sedna/`, url_en: ``},
{id: `B8B833D4`, jp: `流星`, en: `Meteor`, key: `meteor`, category: `meteor`, url: `https://astro-dic.jp/meteor/`, url_en: ``},
{id: `F8FE760F`, jp: `流星群`, en: `Meteor Shower`, key: `meteor_shower`, category: `meteor`, url: `https://astro-dic.jp/meteor-shower-2/`, url_en: ``},
{id: `D5AF1670`, jp: `しぶんぎ座流星群 (1月)`, en: `Quadrantids`, key: `quadrantids`, category: `meteor`, url: `https://ja.wikipedia.org/wiki/%E3%81%97%E3%81%B6%E3%82%93%E3%81%8E%E5%BA%A7%E6%B5%81%E6%98%9F%E7%BE%A4`, url_en: ``},
{id: `72E05C11`, jp: `ペルセウス座流星群 (8月)`, en: `Perseids`, key: `perseids`, category: `meteor`, url: `https://ja.wikipedia.org/wiki/%E3%83%9A%E3%83%AB%E3%82%BB%E3%82%A6%E3%82%B9%E5%BA%A7%E6%B5%81%E6%98%9F%E7%BE%A4`, url_en: ``},
{id: `B5D51C18`, jp: `ふたご座流星群 (12月)`, en: `Geminids`, key: `geminids`, category: `meteor`, url: `https://ja.wikipedia.org/wiki/%E3%81%B5%E3%81%9F%E3%81%94%E5%BA%A7%E6%B5%81%E6%98%9F%E7%BE%A4`, url_en: ``},
{id: `25804E85`, jp: `隕石`, en: `Meteorite`, key: `meteorite`, category: `meteorite`, url: `https://astro-dic.jp/meteorite/`, url_en: ``},
{id: `A3C61E2D`, jp: `アエンデ隕石`, en: `Allende Meteorite`, key: `allende_meteorite`, category: `meteorite`, url: `https://astro-dic.jp/allende-meteorite/`, url_en: ``},
{id: `6F093D05`, jp: `鉄隕石`, en: `Iron Meteorite`, key: `iron_meteorite`, category: `meteorite`, url: `https://astro-dic.jp/iron-meteorite-2/`, url_en: ``},
{id: `D4A8884F`, jp: `クレーター`, en: `Crater`, key: `crater`, category: `meteorite`, url: `https://astro-dic.jp/crater-2/`, url_en: ``},
{id: `B2ED25D4`, jp: `地球`, en: `Earth`, key: `earth`, category: `earth`, url: `https://astro-dic.jp/earth/`, url_en: ``},
{id: `91D2B944`, jp: `オーロラ`, en: `Earth Aurora`, key: `earth_aurora`, category: `earth`, url: `https://astro-dic.jp/aurora/`, url_en: ``},
{id: `B800C744`, jp: `地球磁気圏`, en: `Earth Magnetosphere`, key: `earth_magnetosphere`, category: `earth`, url: `https://astro-dic.jp/magnetosphere-2/`, url_en: ``},
{id: `A6993B43`, jp: `磁気圏 (木星)`, en: `Jupiter Magnetosphere`, key: `jupiter_magnetosphere`, category: `jupiter`, url: ``, url_en: ``},
{id: `4BC01C38`, jp: `磁気圏 (土星)`, en: `Saturn Magnetosphere`, key: `saturn_magnetosphere`, category: `saturn`, url: ``, url_en: ``},
{id: `3BB40691`, jp: `地磁気嵐`, en: `Geomagnetic Storm`, key: `geomagnetic_storm`, category: `earth`, url: `https://astro-dic.jp/magnetic-storm/`, url_en: ``},
{id: `F6F6F204`, jp: `テクタイト`, en: `Tektite`, key: `tektite`, category: `earth`, url: `https://astro-dic.jp/tektite/`, url_en: ``},
{id: `B5D84430`, jp: `電離圏`, en: `Earth Ionosphere`, key: `earth_ionosphere`, category: `earth`, url: `https://astro-dic.jp/ionosphere/`, url_en: ``},
{id: `C7EA354A`, jp: `電離圏 (火星)`, en: `Mars Ionosphere`, key: `mars_ionosphere`, category: `mars`, url: `https://astro-dic.jp/ionosphere/`, url_en: ``},
{id: `E50743D1`, jp: `放射線帯`, en: `Radiation Belt`, key: `radiation_belt`, category: `earth`, url: `https://astro-dic.jp/radiation-belt/`, url_en: ``},
{id: `82D3BD8E`, jp: `バンアレン帯`, en: `Van Allen Radiation Belt`, key: `van_allen_radiation_belt`, category: `earth`, url: `https://astro-dic.jp/van-allen-radiation-belt/`, url_en: ``},
{id: `5CEA98B8`, jp: `ロスビー波`, en: `Rossby Wave`, key: `rossby_wave`, category: `earth`, url: `https://astro-dic.jp/rossby-wave/`, url_en: ``},
{id: `E44BB74B`, jp: `オゾン層`, en: `Ozone Layer`, key: `ozone_layer`, category: `earth`, url: `https://astro-dic.jp/ozone-layer/`, url_en: ``},
{id: `E7A0915D`, jp: `太陽系`, en: `Solar System`, key: `solar_system`, category: `solar_system`, url: `https://astro-dic.jp/solar-system/`, url_en: ``},
{id: `5757F8E6`, jp: `太陽圏`, en: `Heliosphere`, key: `heliosphere`, category: `solar_system`, url: `https://astro-dic.jp/heliosphere/`, url_en: ``},
{id: `DADB8024`, jp: `オールトの雲`, en: `Oort Cloud`, key: `oort_cloud`, category: `solar_system`, url: `https://astro-dic.jp/oort-cloud/`, url_en: ``},
{id: `738AD88F`, jp: `オウムアムア`, en: `Oumuamua`, key: `oumuamua`, category: `solar_system`, url: `https://astro-dic.jp/oumuamua/`, url_en: ``},
{id: `8E698473`, jp: `太陽フレア`, en: `Solar Flare`, key: `solar_flare`, category: `sun`, url: `https://astro-dic.jp/solar-flare/`, url_en: ``},
{id: `7C205969`, jp: `コロナ`, en: `Solar Corona`, key: `solar_corona`, category: `sun`, url: `https://astro-dic.jp/solar-corona/`, url_en: ``},
{id: `2261CDD0`, jp: `コロナ加熱`, en: `Coronal Heating`, key: `coronal_heating`, category: `sun`, url: `https://astro-dic.jp/coronal-heating/`, url_en: ``},
{id: `B8A1BEE8`, jp: `コロナ質量放出`, en: `Coronal Mass Ejection`, key: `coronal_mass_ejection`, category: `sun`, url: `https://astro-dic.jp/coronal-mass-ejection/`, url_en: ``},
{id: `358F8903`, jp: `コロナ磁場`, en: `Coronal Magnetic Field`, key: `coronal_magnetic_field`, category: `sun`, url: `https://astro-dic.jp/coronal-magnetic-field/`, url_en: ``},
{id: `F784E0AE`, jp: `コロナホール`, en: `Coronal Hole`, key: `coronal_hole`, category: `sun`, url: `https://astro-dic.jp/coronal-hole/`, url_en: ``},
{id: `A181EC37`, jp: `コロナループ`, en: `Coronal Loop`, key: `coronal_loop`, category: `sun`, url: `https://astro-dic.jp/coronal-loop/`, url_en: ``},
{id: `8CBDCD6B`, jp: `コロナレイン`, en: `Coronal Rain`, key: `coronal_rain`, category: `sun`, url: `https://astro-dic.jp/coronal-rain/`, url_en: ``},
{id: `FC2C1585`, jp: `太陽磁気嵐`, en: `Solar Magnetic Storm`, key: `solar_magnetic_storm`, category: `sun`, url: `https://astro-dic.jp/magnetic-storm/`, url_en: ``},
{id: `2E8E9300`, jp: `太陽風`, en: `Solar Wind`, key: `solar_wind`, category: `sun`, url: `https://astro-dic.jp/solar-wind/`, url_en: ``},
{id: `A676B519`, jp: `プロミネンス`, en: `Prominence`, key: `prominence`, category: `sun`, url: `https://astro-dic.jp/prominence/`, url_en: ``},
{id: `CB4A4322`, jp: `黒点`, en: `Sunspot`, key: `sunspot`, category: `sun`, url: `https://astro-dic.jp/sunspot/`, url_en: ``},
{id: `EED0ABC3`, jp: `彩層`, en: `Chromosphere`, key: `chromosphere`, category: `sun`, url: `https://astro-dic.jp/chromosphere/`, url_en: ``},
{id: `C07D7E94`, jp: `光球`, en: `Photosphere`, key: `photosphere`, category: `sun`, url: `https://astro-dic.jp/photosphere/`, url_en: ``},
{id: `15EB1F22`, jp: `恒星`, en: `Star`, key: `star`, category: `stars`, url: `https://astro-dic.jp/fixed-star/`, url_en: ``},
{id: `404029CF`, jp: `原始星`, en: `Protostar`, key: `protostar`, category: `stars`, url: `https://astro-dic.jp/protostar/`, url_en: ``},
{id: `55A0ACBC`, jp: `Tタウリ型星`, en: `T Tauri Star`, key: `t_tauri_star`, category: `stars`, url: `https://astro-dic.jp/t-tauri-star-2/`, url_en: ``},
{id: `819910BA`, jp: `褐色矮星`, en: `Brown Dwarf`, key: `brown_dwarf`, category: `stars`, url: `https://astro-dic.jp/brown-dwarf/`, url_en: ``},
{id: `DDCEB69A`, jp: `主系列星`, en: `Star`, key: `star`, category: `stars`, url: `https://astro-dic.jp/main-sequence-star/`, url_en: ``},
{id: `FE159538`, jp: `ウォルフ-ライエ星`, en: `Wolf-Rayet Star`, key: `wolf-rayet_star`, category: `stars`, url: `https://astro-dic.jp/wolf-rayet-star/`, url_en: ``},
{id: `BBE2FA5C`, jp: `赤色巨星`, en: `Red Giant Star`, key: `red_giant_star`, category: `stars`, url: `https://astro-dic.jp/red-giant-star/`, url_en: ``},
{id: `3644BCC6`, jp: `白色矮星`, en: `White Dwarf`, key: `white_dwarf`, category: `stars`, url: `https://astro-dic.jp/white-dwarf/`, url_en: ``},
{id: `EF4EE7E3`, jp: `青色はぐれ星`, en: `Blue Straggler`, key: `blue_straggler`, category: `stars`, url: `https://astro-dic.jp/blue-straggler/`, url_en: ``},
{id: `91E62EE9`, jp: `超新星`, en: `Supernova`, key: `supernova`, category: `supernova`, url: `https://astro-dic.jp/supernova/`, url_en: ``},
{id: `5A356AB9`, jp: `超新星1987A`, en: `Supernova 1987A`, key: `supernova_1987a`, category: `supernova`, url: `https://astro-dic.jp/supernova-1987a/`, url_en: ``},
{id: `1492F470`, jp: `Ⅰa型超新星`, en: `Type-Ia Supernova`, key: `type-ia_supernova`, category: `supernova`, url: `https://astro-dic.jp/type-1a-supernova/`, url_en: ``},
{id: `91BF1AD3`, jp: `Ⅱ型超新星`, en: `Type Ii Supernova`, key: `type_ii_supernova`, category: `supernova`, url: `https://astro-dic.jp/type-2-supernova-2/`, url_en: ``},
{id: `05AF17A8`, jp: `変光星`, en: `Variable Star`, key: `variable_star`, category: `variable_star`, url: `https://astro-dic.jp/variable-star/`, url_en: ``},
{id: `C7CC097C`, jp: `セファイド変光星`, en: `Cepheid`, key: `cepheid`, category: `variable_star`, url: `https://astro-dic.jp/cepheid/`, url_en: ``},
{id: `DFD06B08`, jp: `高光度青色変光星`, en: `Luminous Blue Variable`, key: `luminous_blue_variable`, category: `variable_star`, url: `https://astro-dic.jp/luminous-blue-variable/`, url_en: ``},
{id: `8F799C05`, jp: `分子雲`, en: `Molecular Cloud`, key: `molecular_cloud`, category: `Interstellar matter`, url: `https://astro-dic.jp/molecular-cloud/`, url_en: ``},
{id: `01B814DD`, jp: `グロビュール`, en: `Globule`, key: `globule`, category: `Interstellar matter`, url: `https://astro-dic.jp/globule/`, url_en: ``},
{id: `3A662B40`, jp: `HⅡ領域`, en: `Hii Region`, key: `hii_region`, category: `Interstellar matter`, url: `https://astro-dic.jp/h2-region/`, url_en: ``},
{id: `A6C1AEBC`, jp: `恒星間天体`, en: `Interstellar Object`, key: `interstellar_object`, category: `Interstellar matter`, url: `https://astro-dic.jp/interstellar-object/`, url_en: ``},
{id: `150358DE`, jp: `星雲`, en: `Nebula`, key: `nebula`, category: `nebula`, url: `https://astro-dic.jp/gaseous-nebula/`, url_en: ``},
{id: `A7840E8D`, jp: `輝線星雲`, en: `Emission Line Nebula`, key: `emission_line_nebula`, category: `nebula`, url: `https://astro-dic.jp/emission-line-nebula/`, url_en: ``},
{id: `27E350A7`, jp: `暗黒星雲`, en: `Dark Nebula`, key: `dark_nebula`, category: `nebula`, url: `https://astro-dic.jp/dark-nebula/`, url_en: ``},
{id: `CA8D0DBD`, jp: `反射星雲`, en: `Reflection Nebula`, key: `reflection_nebula`, category: `nebula`, url: `https://astro-dic.jp/reflection-nebula/`, url_en: ``},
{id: `19FC68A8`, jp: `惑星状星雲`, en: `Planetary Nebula`, key: `planetary_nebula`, category: `nebula`, url: `https://astro-dic.jp/planetary-nebula/`, url_en: ``},
{id: `F1E2DEE8`, jp: `原始惑星状星雲`, en: `Protoplanetary Nebula`, key: `protoplanetary_nebula`, category: `nebula`, url: `https://astro-dic.jp/protoplanetary-nebula/`, url_en: ``},
{id: `CFA1D663`, jp: `オリオン大星雲`, en: `Orion Nebula`, key: `orion_nebula`, category: `nebula`, url: `https://astro-dic.jp/orion-nebula/`, url_en: ``},
{id: `F98ACC85`, jp: `オリオン大星雲`, en: `Orion Nebula`, key: `orion_nebula`, category: `star_formation`, url: `https://astro-dic.jp/orion-nebula/`, url_en: ``},
{id: `D2A767AF`, jp: `かに星雲`, en: `Crab Nebula`, key: `crab_nebula`, category: `nebula`, url: `https://astro-dic.jp/crab-nebula/`, url_en: ``},
{id: `7EFE6F06`, jp: `かに星雲`, en: `Crab Nebula`, key: `crab_nebula`, category: `supernova_remnant`, url: `https://astro-dic.jp/crab-nebula/`, url_en: ``},
{id: `0D117A9C`, jp: `星形成`, en: `Star Formation`, key: `star_formation`, category: `star_formation`, url: `https://astro-dic.jp/star-formation2/`, url_en: ``},
{id: `3675AE42`, jp: `星形成領域`, en: `Star Forming Regions`, key: `star_forming_regions`, category: `star_formation`, url: `https://astro-dic.jp/star-forming-regions/`, url_en: ``},
{id: `F811A1FE`, jp: `HH天体`, en: `HH Object`, key: `hh_object`, category: `star_formation`, url: `https://astro-dic.jp/hh-object/`, url_en: ``},
{id: `AA7D2826`, jp: `分子流`, en: `Molecular Outflow`, key: `molecular_outflow`, category: `star_formation`, url: `https://astro-dic.jp/molecular-outflow/`, url_en: ``},
{id: `D823ADDB`, jp: `原始惑星`, en: `Protoplanet`, key: `protoplanet`, category: `star_formation`, url: `https://astro-dic.jp/protoplanet/`, url_en: ``},
{id: `D9B5C936`, jp: `原始惑星系円盤`, en: `Protoplanetary Disk`, key: `protoplanetary_disk`, category: `star_formation`, url: `https://astro-dic.jp/protoplanetary-disk/`, url_en: ``},
{id: `AC260CA1`, jp: `星周円盤`, en: `Circumstellar Disk`, key: `circumstellar_disk`, category: `star_formation`, url: `https://astro-dic.jp/circumstellar-disk/`, url_en: ``},
{id: `C713AFAD`, jp: `原始星`, en: `Protostar`, key: `protostar`, category: `star_formation`, url: `https://astro-dic.jp/protostar/`, url_en: ``},
{id: `0383B595`, jp: `星団`, en: `Star Cluster`, key: `star_cluster`, category: `star_cluster`, url: `https://astro-dic.jp/star-cluster/`, url_en: ``},
{id: `B7BFACCB`, jp: `球状星団`, en: `Globular Cluster`, key: `globular_cluster`, category: `star_cluster`, url: `https://astro-dic.jp/globular-cluster/`, url_en: ``},
{id: `5E3512ED`, jp: `散開星団`, en: `Open Cluster`, key: `open_cluster`, category: `star_cluster`, url: `https://astro-dic.jp/open-cluster/`, url_en: ``},
{id: `181FF627`, jp: `運動星団`, en: `Moving Cluster`, key: `moving_cluster`, category: `star_cluster`, url: `https://astro-dic.jp/moving-cluster/`, url_en: ``},
{id: `1BC09F82`, jp: `天の川`, en: `Milky Way`, key: `milky_way`, category: `milky_way`, url: `https://astro-dic.jp/milky-way/`, url_en: ``},
{id: `3CC1DB50`, jp: `天の川銀河`, en: `Milky Way Galaxy`, key: `milky_way_galaxy`, category: `milky_way`, url: `https://astro-dic.jp/milky-way-galaxy/`, url_en: ``},
{id: `5BBB2D54`, jp: `銀河系`, en: `The Galaxy`, key: `the_galaxy`, category: `milky_way`, url: `https://astro-dic.jp/the-galaxy/`, url_en: ``},
{id: `E5279741`, jp: `いて座A`, en: `Sagittarius A`, key: `sagittarius_a`, category: `milky_way`, url: `https://astro-dic.jp/sgr-a/`, url_en: ``},
{id: `C5D30304`, jp: `いて座A*`, en: `Sagittarius A Black Hole`, key: `sagittarius_a_black_hole`, category: `milky_way`, url: `https://astro-dic.jp/sgr-a-star/`, url_en: ``},
{id: `5B1A8D46`, jp: `アンドロメダ銀河`, en: `Andromeda Galaxy`, key: `andromeda_galaxy`, category: `local_group`, url: `https://astro-dic.jp/andromeda-galaxy/`, url_en: ``},
{id: `A8704EB4`, jp: `さんかく座銀河`, en: `Triangulum Galaxy`, key: `triangulum_galaxy`, category: `local_group`, url: `https://ja.wikipedia.org/wiki/%E3%81%95%E3%82%93%E3%81%8B%E3%81%8F%E5%BA%A7%E9%8A%80%E6%B2%B3`, url_en: ``},
{id: `A25386DA`, jp: `小マゼラン雲`, en: `Small Magellanic Cloud`, key: `small_magellanic_cloud`, category: `local_group`, url: `https://astro-dic.jp/small-magellanic-cloud/`, url_en: ``},
{id: `9EA894D7`, jp: `大マゼラン雲`, en: `Large Magellanic Cloud`, key: `large_magellanic_cloud`, category: `local_group`, url: `https://astro-dic.jp/large-magellanic-cloud/`, url_en: ``},
{id: `9F4FC8F0`, jp: `局所銀河群`, en: `Local Group`, key: `local_group`, category: `local_group`, url: `https://astro-dic.jp/local-group/`, url_en: ``},
{id: `4FEA1DA8`, jp: `銀河群`, en: `Group of Galaxies`, key: `group_of_galaxies`, category: `local_group`, url: `https://astro-dic.jp/group-of-galaxies/`, url_en: ``},
{id: `B2430FB0`, jp: `コンパクト銀河群`, en: `Compact Group of Galaxies`, key: `compact_group_of_galaxies`, category: `local_group`, url: `https://astro-dic.jp/compact-group-of-galaxies/`, url_en: ``},
{id: `689F87CB`, jp: `渦巻銀河`, en: `Spiral Galaxy`, key: `spiral_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/spiral-galaxy/`, url_en: ``},
{id: `9983C94E`, jp: `棒渦巻銀河`, en: `Barred Spiral Galaxy`, key: `barred_spiral_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/barred-spiral-galaxy-2/`, url_en: ``},
{id: `A25AFF1A`, jp: `渦巻腕`, en: `Spiral Arm`, key: `spiral_arm`, category: `galaxy_category`, url: `https://astro-dic.jp/spiral-arm/`, url_en: ``},
{id: `B6D021E6`, jp: `銀河ハロー`, en: `Galactic Halo`, key: `galactic_halo`, category: `galaxy_category`, url: `https://astro-dic.jp/galactic-halo/`, url_en: ``},
{id: `471BC189`, jp: `レンズ状銀河`, en: `Lenticular Galaxy`, key: `lenticular_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/lenticular-galaxy/`, url_en: ``},
{id: `119FB3D2`, jp: `S0銀河`, en: `S0 Galaxy`, key: `s0_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/s0-galaxy/`, url_en: ``},
{id: `B537F10F`, jp: `楕円銀河`, en: `Elliptical Galaxy`, key: `elliptical_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/elliptical-galaxy/`, url_en: ``},
{id: `BF9EF244`, jp: `銀河バルジ`, en: `Galactic Bulge`, key: `galactic_bulge`, category: `galaxy_category`, url: `https://astro-dic.jp/galactic-bulge/`, url_en: ``},
{id: `E39FDBB3`, jp: `矮小銀河`, en: `Dwarf Galaxy`, key: `dwarf_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/dwarf-galaxy/`, url_en: ``},
{id: `28AE9FDF`, jp: `青色コンパクト矮小銀河`, en: `Blue Compact Dwarf Galaxy`, key: `blue_compact_dwarf_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/blue-compact-dwarf-galaxy/`, url_en: ``},
{id: `0FCF3567`, jp: `孤立銀河`, en: `Isolated Galaxy`, key: `isolated_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/isolated-galaxy/`, url_en: ``},
{id: `E692E7D9`, jp: `低表面輝度銀河`, en: `Low-Surface-Brightness Galaxy`, key: `low-surface-brightness_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/low-surface-brightness-galaxy/`, url_en: ``},
{id: `9B13F5E2`, jp: `特異銀河`, en: `Peculiar Galaxy`, key: `peculiar_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/peculiar-galaxy/`, url_en: ``},
{id: `9F22EBC7`, jp: `子持ち銀河`, en: `Whirlpool Galaxy`, key: `whirlpool_galaxy`, category: `galaxy_category`, url: `https://ja.wikipedia.org/wiki/%E5%AD%90%E6%8C%81%E3%81%A1%E9%8A%80%E6%B2%B3`, url_en: ``},
{id: `A319CB0B`, jp: `相互作用銀河`, en: `Interacting Galaxies`, key: `interacting_galaxies`, category: `galaxy_category`, url: `https://astro-dic.jp/interacting-galaxies/`, url_en: ``},
{id: `1382DAF4`, jp: `不規則銀河`, en: `Irregular Galaxy`, key: `irregular_galaxy`, category: `galaxy_category`, url: `https://astro-dic.jp/irregular-galaxy/`, url_en: ``},
{id: `3D2459BB`, jp: `銀河合体`, en: `Galaxy Merging`, key: `galaxy_merging`, category: `galaxy_category`, url: `https://astro-dic.jp/galaxy-merging/`, url_en: ``},
{id: `F4FFE531`, jp: `銀河衝撃波`, en: `Galactic Shock`, key: `galactic_shock`, category: `galaxy_category`, url: `https://astro-dic.jp/galactic-shock/`, url_en: ``},
{id: `0B51BA11`, jp: `銀河風`, en: `Galactic Wind`, key: `galactic_wind`, category: `galaxy_category`, url: `https://astro-dic.jp/galactic-wind/`, url_en: ``},
{id: `B1C6A2DA`, jp: `銀河の中心核`, en: `Galactic Nucleus`, key: `galactic_nucleus`, category: `galaxy_category`, url: `https://astro-dic.jp/galactic-nucleus-2/`, url_en: ``},
{id: `7AE1EBE3`, jp: `ダークレーン`, en: `Dark Lane`, key: `dark_lane`, category: `galaxy_category`, url: `https://astro-dic.jp/dark-lane/`, url_en: ``},
{id: `FE21BD9A`, jp: `銀河`, en: `Active Galaxy`, key: `active_galaxy`, category: `active_galaxy`, url: `https://astro-dic.jp/active-galaxy/`, url_en: ``},
{id: `A1172D03`, jp: `活動銀河核`, en: `Active Galactic Nucleus`, key: `active_galactic_nucleus`, category: `active_galaxy`, url: `https://astro-dic.jp/active-galactic-nucleus/`, url_en: ``},
{id: `1B77F5CB`, jp: `セイファート銀河`, en: `Seyfert Galaxy`, key: `seyfert_galaxy`, category: `active_galaxy`, url: `https://astro-dic.jp/seyfert-galaxy/`, url_en: ``},
{id: `DD0E702A`, jp: `クェーサー`, en: `Quasar`, key: `quasar`, category: `active_galaxy`, url: `https://astro-dic.jp/quasar/`, url_en: ``},
{id: `D21DD2BE`, jp: `BALクェーサー`, en: `Broad Absorption Line Quasar`, key: `broad_absorption_line_quasar`, category: `active_galaxy`, url: `https://astro-dic.jp/broad-absorption-line-quasar/`, url_en: ``},
{id: `0F2E5CC0`, jp: `ライナー銀河中心核`, en: `Low-Ionization Nuclear Emission Line Region`, key: `low-ionization_nuclear_emission_line_region`, category: `active_galaxy`, url: `https://astro-dic.jp/low-ionization-nuclear-emission-line-region/`, url_en: ``},
{id: `5F8095FA`, jp: `とかげ座BL型天体`, en: `BL Lacertae`, key: `bl_lacertae`, category: `active_galaxy`, url: `https://astro-dic.jp/bl-lacertae-object/`, url_en: ``},
{id: `FDBE99DA`, jp: `スーパーウィンド銀河`, en: `Superwind Galaxy`, key: `superwind_galaxy`, category: `active_galaxy`, url: `https://astro-dic.jp/superwind-galaxy/`, url_en: ``},
{id: `B475435E`, jp: `スターバースト`, en: `Starburst`, key: `starburst`, category: `active_galaxy`, url: `https://astro-dic.jp/starburst/`, url_en: ``},
{id: `F9204913`, jp: `スターバースト銀河`, en: `Starburst Galaxy`, key: `starburst_galaxy`, category: `active_galaxy`, url: `https://astro-dic.jp/starburst-galaxy-2/`, url_en: ``},
{id: `D0CFD13F`, jp: `マルカリアン銀河`, en: `Markarian Galaxy`, key: `markarian_galaxy`, category: `active_galaxy`, url: `https://astro-dic.jp/markarian-galaxy/`, url_en: ``},
{id: `CC3BF09D`, jp: `超高光度赤外線銀河`, en: `Ultra Luminous Infrared Galaxy`, key: `ultra_luminous_infrared_galaxy`, category: `active_galaxy`, url: `https://astro-dic.jp/ultra-luminous-infrared-galaxy/`, url_en: ``},
{id: `AF13D6CE`, jp: `ブレーザー`, en: `Blazar`, key: `blazar`, category: `active_galaxy`, url: `https://astro-dic.jp/blazar/`, url_en: ``},
{id: `BE4844A8`, jp: `天の川銀河`, en: `Milky Way Galaxy`, key: `milky_way_galaxy`, category: `galaxies`, url: `https://astro-dic.jp/milky-way-galaxy/`, url_en: ``},
{id: `7E514DD8`, jp: `アンドロメダ銀河`, en: `Andromeda Galaxy`, key: `andromeda_galaxy`, category: `galaxies`, url: `https://astro-dic.jp/andromeda-galaxy/`, url_en: ``},
{id: `D5508116`, jp: `さんかく座銀河`, en: `Triangulum Galaxy`, key: `triangulum_galaxy`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/%E3%81%95%E3%82%93%E3%81%8B%E3%81%8F%E5%BA%A7%E9%8A%80%E6%B2%B3`, url_en: ``},
{id: `1E55341A`, jp: `小マゼラン雲`, en: `Small Magellanic Cloud`, key: `small_magellanic_cloud`, category: `galaxies`, url: `https://astro-dic.jp/small-magellanic-cloud/`, url_en: ``},
{id: `8C184EF4`, jp: `大マゼラン雲`, en: `Large Magellanic Cloud`, key: `large_magellanic_cloud`, category: `galaxies`, url: `https://astro-dic.jp/large-magellanic-cloud/`, url_en: ``},
{id: `4C7F2B86`, jp: `M87`, en: `Messier 87`, key: `messier_87`, category: `galaxies`, url: `https://astro-dic.jp/m87/`, url_en: `https://en.wikipedia.org/wiki/Messier_87`},
{id: `E566604B`, jp: `NGC4038 / NGC4039`, en: `Antennae Galaxies`, key: `antennae_galaxies`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/%E8%A7%A6%E8%A7%92%E9%8A%80%E6%B2%B3`, url_en: `https://en.wikipedia.org/wiki/Antennae_Galaxies`},
{id: `5B0A661C`, jp: `車輪銀河`, en: `Cartwheel Galaxy`, key: `cartwheel_galaxy`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/%E8%BB%8A%E8%BC%AA%E9%8A%80%E6%B2%B3`, url_en: `https://en.wikipedia.org/wiki/Cartwheel_Galaxy`},
{id: `C19E3F45`, jp: `ESO 97-G13`, en: `Circinus Galaxy`, key: `circinus_galaxy`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/ESO_97-G13`, url_en: `https://en.wikipedia.org/wiki/Circinus_Galaxy`},
{id: `EAA97024`, jp: `NGC 2841`, en: `Pinwheel Galaxy`, key: `pinwheel_galaxy`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/%E7%BE%8A%E6%AF%9B%E7%8A%B6%E6%B8%A6%E5%B7%BB%E9%8A%80%E6%B2%B3`, url_en: `https://en.wikipedia.org/wiki/Pinwheel_Galaxy`},
{id: `DD24FE1F`, jp: `おたまじゃくし銀河`, en: `Tadpole Galaxy`, key: `tadpole_galaxy`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/%E3%81%8A%E3%81%9F%E3%81%BE%E3%81%98%E3%82%83%E3%81%8F%E3%81%97%E9%8A%80%E6%B2%B3`, url_en: `https://en.wikipedia.org/wiki/Tadpole_Galaxy`},
{id: `0439B45D`, jp: `NGC 1300`, en: `NGC 1300`, key: `ngc_1300`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/NGC_1300`, url_en: `https://en.wikipedia.org/wiki/NGC_1300`},
{id: `1D93BEF6`, jp: `NGC 4622`, en: `NGC 4622`, key: `ngc_4622`, category: `galaxies`, url: `https://en.wikipedia.org/wiki/NGC_4622`, url_en: `https://en.wikipedia.org/wiki/NGC_4622`},
{id: `474CC62F`, jp: `M64`, en: `M64`, key: `m64`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/%E9%BB%92%E7%9C%BC%E9%8A%80%E6%B2%B3`, url_en: `https://en.wikipedia.org/wiki/Black_Eye_Galaxy`},
{id: `3C764776`, jp: `M81`, en: `Messier 81`, key: `messier_81`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/M81_(%E5%A4%A9%E4%BD%93)`, url_en: `https://en.wikipedia.org/wiki/Messier_81`},
{id: `2792C918`, jp: `M82`, en: `Messier 82`, key: `messier_82`, category: `galaxies`, url: `https://ja.wikipedia.org/wiki/M82_(%E5%A4%A9%E4%BD%93)`, url_en: `https://en.wikipedia.org/wiki/Messier_82`},
{id: `4F8312D6`, jp: `銀河団`, en: `Galaxy Cluster`, key: `galaxy_cluster`, category: `galaxy_cluster`, url: `https://astro-dic.jp/cluster-of-galaxies/`, url_en: ``},
{id: `78128BD5`, jp: `おとめ座銀河団`, en: `Virgo Cluster`, key: `virgo_cluster`, category: `galaxy_cluster`, url: `https://astro-dic.jp/virgo-cluster/`, url_en: ``},
{id: `BB1D9884`, jp: `Abell 68`, en: `Abell 68`, key: `abell_68`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `ACD12656`, jp: `Abell 370`, en: `Abell 370`, key: `abell_370`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `4BCAB801`, jp: `Abell 383`, en: `Abell 383`, key: `abell_383`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `435431DE`, jp: `Abell 399`, en: `Abell 399`, key: `abell_399`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `414A8108`, jp: `Abell 401`, en: `Abell 401`, key: `abell_401`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `F586EE7A`, jp: `Abell 520`, en: `Abell 520`, key: `abell_520`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `3189CBC2`, jp: `Abell 1656`, en: `Abell 1656`, key: `abell_1656`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `9A3BE97B`, jp: `Abell 1689`, en: `Abell 1689`, key: `abell_1689`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `B5D153FC`, jp: `Abell 1763`, en: `Abell 1763`, key: `abell_1763`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `9809F8D9`, jp: `Abell 2125 `, en: `Abell 2125 `, key: `abell_2125_`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `A8BF4893`, jp: `Abell 2744`, en: `Abell 2744`, key: `abell_2744`, category: `galaxy_cluster`, url: ``, url_en: ``},
{id: `5BDCA219`, jp: `おとめ座銀河団`, en: `Virgo Cluster`, key: `virgo_cluster`, category: `galaxy_cluster`, url: `https://astro-dic.jp/virgo-cluster/`, url_en: ``},
{id: `62F38BC0`, jp: `超銀河団`, en: `Supercluster Of Galaxies`, key: `supercluster_of_galaxies`, category: `galaxy_cluster`, url: `https://astro-dic.jp/supercluster-of-galaxies/`, url_en: ``},
{id: `797D39FA`, jp: `中性子星`, en: `Neutron Star`, key: `neutron_star`, category: `neutron_star`, url: `https://astro-dic.jp/neutron-star/`, url_en: ``},
{id: `5E260E27`, jp: `パルサー`, en: `Pulsar`, key: `pulsar`, category: `neutron_star`, url: `https://astro-dic.jp/pulsar/`, url_en: ``},
{id: `AADB59DA`, jp: `マグネター`, en: `Magnetar`, key: `magnetar`, category: `neutron_star`, url: `https://astro-dic.jp/magnetar/`, url_en: ``},
{id: `25E1FDCE`, jp: `ブラックホール`, en: `Black Hole`, key: `black_hole`, category: `black_hole`, url: `https://astro-dic.jp/black-hole/`, url_en: ``},
{id: `50307849`, jp: `トーラス`, en: `Torus of Black Hole`, key: `torus_of_black_hole`, category: `black_hole`, url: `https://astro-dic.jp/torus/`, url_en: ``},
{id: `A997BE2D`, jp: `はくちょう座X-1`, en: `Cygnus X-1`, key: `cygnus_x-1`, category: `black_hole`, url: `https://astro-dic.jp/cygnus-x-1/`, url_en: ``},
{id: `F883BAAD`, jp: `超新星残骸`, en: `Supernova Remnant`, key: `supernova_remnant`, category: `supernova_remnant`, url: `https://astro-dic.jp/supernova-remnant/`, url_en: ``},
{id: `3862DA0D`, jp: `宇宙線`, en: `Cosmic Ray`, key: `cosmic_ray`, category: `cosmic_rays`, url: `https://astro-dic.jp/cosmic-ray/`, url_en: ``},
{id: `C4D05461`, jp: `X線源`, en: `X-Ray Source`, key: `x-ray_source`, category: `cosmic_rays`, url: `https://astro-dic.jp/x-ray-source/`, url_en: ``},
{id: `7B0064D3`, jp: `X線バースト`, en: `X-Ray Burst`, key: `x-ray_burst`, category: `cosmic_rays`, url: `https://astro-dic.jp/x-ray-burst/`, url_en: ``},
{id: `A9620861`, jp: `ガンマ線源`, en: `Gamma-Ray Source`, key: `gamma-ray_source`, category: `cosmic_rays`, url: `https://astro-dic.jp/gamma-ray-source/`, url_en: ``},
{id: `27458016`, jp: `ガンマ線バースト`, en: `Gamma-Ray Burst`, key: `gamma-ray_burst`, category: `cosmic_rays`, url: `https://astro-dic.jp/gamma-ray-burst/`, url_en: ``},
{id: `FE209E3D`, jp: `IRTF`, en: `NASA InfraRed Telescope Facility`, key: `nasa_infrared_telescope_facility`, category: `ground_telescopes`, url: `https://astro-dic.jp/nasa-infrared-telescope-facility/`, url_en: ``},
{id: `612CF598`, jp: `アイザックニュートン望遠鏡`, en: `Isaac Newton Telescope`, key: `isaac_newton_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/isaac-newton-telescope/`, url_en: ``},
{id: `E0BC60EA`, jp: `アルマ望遠鏡`, en: `ALMA`, key: `alma`, category: `ground_telescopes`, url: `https://astro-dic.jp/alma-telescope/`, url_en: ``},
{id: `738E2057`, jp: `イベントホライズン`, en: `Event Horizon Telescope`, key: `event_horizon_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/event-horizon-telescope/`, url_en: ``},
{id: `603AFBC2`, jp: `大型双眼望遠鏡`, en: `Large Binocular Telescope`, key: `large_binocular_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/lbt/`, url_en: ``},
{id: `DCFE92DA`, jp: `カイパー飛行機搭載天文台`, en: `Kuiper Airborne Observatory`, key: `kuiper_airborne_observatory`, category: `ground_telescopes`, url: `https://astro-dic.jp/kuiper-airborne-observatory/`, url_en: ``},
{id: `91854889`, jp: `カナダ-フランス-ハワイ望遠鏡`, en: `Canada-France-Hawaii Telescope`, key: `canada-france-hawaii_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/cfht/`, url_en: ``},
{id: `6F832F4B`, jp: `カナリー大型望遠鏡`, en: `Grand Canary Telescope`, key: `grand_canary_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/gran-telescopio-canarias/`, url_en: ``},
{id: `AD8BE123`, jp: `ケック望遠鏡`, en: `Keck Telescope`, key: `keck_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/keck-telescope/`, url_en: ``},
{id: `3ACCAADD`, jp: `広域精測望遠鏡`, en: `VLBI Exploration of Radio Astrometry`, key: `vlbi_exploration_of_radio_astrometry`, category: `ground_telescopes`, url: `https://astro-dic.jp/vlbi-exploration-of-radio-astrometry/`, url_en: ``},
{id: `6CA18B5E`, jp: `500メートル球面電波望遠鏡`, en: `Five-hundred-meter Aperture Spherical radio Telescope`, key: `five-hundred-meter_aperture_spherical_radio_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/five-hundred-meter-aperture-spherical-radio-telescope/`, url_en: ``},
{id: `2406A7BD`, jp: `30m望遠鏡`, en: `Thirty Meter Telescope`, key: `thirty_meter_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/thirty-meter-telescope/`, url_en: ``},
{id: `8507D407`, jp: `CFHT`, en: `CFHT`, key: `cfht`, category: `ground_telescopes`, url: `https://astro-dic.jp/cfht-2/`, url_en: ``},
{id: `DAFFE15D`, jp: `ジェミニ望遠鏡`, en: `Gemini Telescopes`, key: `gemini_telescopes`, category: `ground_telescopes`, url: `https://astro-dic.jp/gemini-telescopes/`, url_en: ``},
{id: `A59B680D`, jp: `すばる望遠鏡`, en: `Subaru Telescope`, key: `subaru_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/subaru-telescope/`, url_en: ``},
{id: `6DE51BF0`, jp: `成層圏赤外線天文台`, en: `Stratospheric Observatory for Infrared Astronomy`, key: `stratospheric_observatory_for_infrared_astronomy`, category: `ground_telescopes`, url: `https://astro-dic.jp/stratospheric-observatory-for-infrared-astronomy/`, url_en: ``},
{id: `6E530529`, jp: `超大型望遠鏡 (VLT)`, en: `Very Large Telescope`, key: `very_large_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/very-large-telescope/`, url_en: ``},
{id: `2A2FC960`, jp: `超長基線電波干渉計群`, en: `Very Long Baseline Array`, key: `very_long_baseline_array`, category: `ground_telescopes`, url: `https://astro-dic.jp/vlba/`, url_en: ``},
{id: `D01D123F`, jp: `NASA赤外線望遠鏡施設`, en: `IRTF`, key: `irtf`, category: `ground_telescopes`, url: `https://astro-dic.jp/nasa-infrared-telescope-facility-2/`, url_en: ``},
{id: `0E049B14`, jp: `超大型電波干渉計群 (VLA)`, en: `Very Large Array`, key: `very_large_array`, category: `ground_telescopes`, url: `https://astro-dic.jp/very-large-array/`, url_en: ``},
{id: `41D53541`, jp: `ヘール望遠鏡`, en: `Hale Telescope`, key: `hale_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/hale-telescope/`, url_en: ``},
{id: `884D714B`, jp: `ホイップルガンマ線望遠鏡`, en: `Fred Lawrence Whipple Observatory`, key: `fred_lawrence_whipple_observatory`, category: `ground_telescopes`, url: `https://astro-dic.jp/whipple-gamma-ray-telescope/`, url_en: ``},
{id: `49CC7D5D`, jp: `ホビー-エバリー望遠鏡`, en: `Hobby-Eberly Telescope`, key: `hobby-eberly_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/hobby-eberly-telescope/`, url_en: ``},
{id: `1A9D60F0`, jp: `メイヨール望遠鏡`, en: `Mayall telescope`, key: `mayall_telescope`, category: `ground_telescopes`, url: `https://astro-dic.jp/mayall-telescope/`, url_en: ``},
{id: `BFF3EBC4`, jp: `インテグラル衛星`, en: `INTEGRAL satellite`, key: `integral_satellite`, category: `space_telescopes`, url: `https://astro-dic.jp/integral-satellite/`, url_en: ``},
{id: `05A4BBEB`, jp: `COBE衛星`, en: `COBE Explorer`, key: `cobe_explorer`, category: `space_telescopes`, url: `https://astro-dic.jp/cosmic-background-explorer/`, url_en: ``},
{id: `BD627E3C`, jp: `XMM-ニュートン衛星`, en: `XMM-Newton telescope`, key: `xmm-newton_telescope`, category: `space_telescopes`, url: `https://astro-dic.jp/x-ray-multi-mirror-mission-newton-satellite/`, url_en: ``},
{id: `1AE659A9`, jp: `OSSE検出器`, en: `Oriented Scintillation Spectrometer Experiment`, key: `oriented_scintillation_spectrometer_experiment`, category: `space_telescopes`, url: `https://astro-dic.jp/osse-detector/`, url_en: ``},
{id: `97ECFDF0`, jp: `ガイア衛星`, en: `Gaia mission`, key: `gaia_mission`, category: `space_telescopes`, url: `https://astro-dic.jp/gaia-satellite/`, url_en: ``},
{id: `2BBE8B6D`, jp: `「きぼう」日本実験棟`, en: `Kibo`, key: `kibo`, category: `space_telescopes`, url: `https://astro-dic.jp/kibo-japanese-experiment-module/`, url_en: ``},
{id: `4D1737B2`, jp: `GALEX衛星`, en: `GALEX`, key: `galex`, category: `space_telescopes`, url: `https://astro-dic.jp/galaxy-evolution-explorer/`, url_en: ``},
{id: `19DF74B9`, jp: `赤外線天文衛星`, en: `Infrared Astronomical Satellite`, key: `infrared_astronomical_satellite`, category: `space_telescopes`, url: `https://astro-dic.jp/infrared-astronomical-satellite/`, url_en: ``},
{id: `F40B63C9`, jp: `SOHO`, en: `Solar and Heliospheric Observatory`, key: `solar_and_heliospheric_observatory`, category: `space_telescopes`, url: `https://astro-dic.jp/soho/`, url_en: ``},
{id: `FF6DBC3B`, jp: `WMAP衛星`, en: `WMAP satellite`, key: `wmap_satellite`, category: `space_telescopes`, url: `https://astro-dic.jp/wmap-satellite/`, url_en: ``},
{id: `DBBDD9C5`, jp: `チャンドラ衛星`, en: `Chandra X-ray Observatory`, key: `chandra_x-ray_observatory`, category: `space_telescopes`, url: `https://astro-dic.jp/chandra-x-ray-observatory/`, url_en: ``},
{id: `2823C5E2`, jp: `ニュースター衛星`, en: `NuSTAR`, key: `nustar`, category: `space_telescopes`, url: `https://astro-dic.jp/nustar-satellite/`, url_en: ``},
{id: `DE3060F6`, jp: `ハーシェル宇宙天文台`, en: `Herschel Space Observatory`, key: `herschel_space_observatory`, category: `space_telescopes`, url: `https://astro-dic.jp/herschel-space-observatory/`, url_en: ``},
{id: `0890EE85`, jp: `BATSE検出器`, en: `BATSE detector`, key: `batse_detector`, category: `space_telescopes`, url: `https://astro-dic.jp/burst-and-transient-source-experiment-detector/`, url_en: ``},
{id: `BD29B077`, jp: `ハッブル宇宙望遠鏡`, en: `Hubble Space Telescope`, key: `hubble_space_telescope`, category: `space_telescopes`, url: `https://astro-dic.jp/hubble-space-telescope/`, url_en: ``},
{id: `17ED793B`, jp: `ひので衛星`, en: `Hinode`, key: `hinode`, category: `space_telescopes`, url: `https://astro-dic.jp/hinode-satellite/`, url_en: ``},
{id: `74EAF883`, jp: `フェルミ衛星`, en: `Fermi Gamma-ray Space Telescope`, key: `fermi_gamma-ray_space_telescope`, category: `space_telescopes`, url: `https://astro-dic.jp/fermi-gamma-ray-space-telescope/`, url_en: ``},
{id: `735322E8`, jp: `プランク衛星`, en: `Planck`, key: `planck`, category: `space_telescopes`, url: `https://astro-dic.jp/planck-satellite/`, url_en: ``},
{id: `CFB680EB`, jp: `MAXI`, en: `MAXI`, key: `maxi`, category: `space_telescopes`, url: `https://astro-dic.jp/maxi/`, url_en: ``},
{id: `B9B594DA`, jp: `ようこう衛星`, en: `Yohkoh satellite`, key: `yohkoh_satellite`, category: `space_telescopes`, url: `https://astro-dic.jp/yohkoh-satellite/`, url_en: ``},
{id: `F697B66C`, jp: `ROSAT衛星`, en: `ROSAT`, key: `rosat`, category: `space_telescopes`, url: `https://astro-dic.jp/rosat/`, url_en: ``},
{id: `4DF5220A`, jp: `ローマン宇宙望遠鏡`, en: `Wide Field Infrared Survey Telescope`, key: `wide_field_infrared_survey_telescope`, category: `space_telescopes`, url: `https://astro-dic.jp/roman-space-telescope-2/`, url_en: ``},
{id: `A20E39C5`, jp: `ボイジャー探査機`, en: `Voyager`, key: `voyager`, category: `space_probes_outer_planetary`, url: `https://astro-dic.jp/voyager/`, url_en: ``},
{id: `83198B6B`, jp: `ニューホライズンズ探査機`, en: `New Horizons`, key: `new_horizons`, category: `space_probes_pluto`, url: `https://astro-dic.jp/new-horizons/`, url_en: ``},
{id: `1D42C360`, jp: `カッシーニ探査機`, en: `Cassini`, key: `cassini`, category: `space_probes_saturn`, url: `https://astro-dic.jp/cassini/`, url_en: ``},
{id: `7D69B8F6`, jp: `ガリレオ探査機`, en: `Galileo Spacecraft`, key: `galileo_spacecraft`, category: `space_probes_jupiter`, url: `https://astro-dic.jp/galileo/`, url_en: ``},
{id: `D185F004`, jp: `オポチュニティ`, en: `Mars Rover Opportunity`, key: `mars_rover_opportunity`, category: `space_probes_mars`, url: `https://astro-dic.jp/opportunity/`, url_en: ``},
{id: `54F09F06`, jp: `キュリオシティ`, en: `Mars Rover Curiosity`, key: `mars_rover_curiosity`, category: `space_probes_mars`, url: `https://astro-dic.jp/curiosity/`, url_en: ``},
{id: `23464CB2`, jp: `スピリット`, en: `Mars Rover Spirit`, key: `mars_rover_spirit`, category: `space_probes_mars`, url: `https://astro-dic.jp/spirit/`, url_en: ``},
{id: `424EC35E`, jp: `パーサビアランス`, en: `Mars Rover Perseverance`, key: `mars_rover_perseverance`, category: `space_probes_mars`, url: `https://astro-dic.jp/perseverance/`, url_en: ``},
{id: `3EAC2F23`, jp: `バイキング探査機`, en: `Viking`, key: `viking`, category: `space_probes_mars`, url: `https://astro-dic.jp/viking/`, url_en: ``},
{id: `08BB139C`, jp: `フェニックス探査機`, en: `Phoenix Mars Lander`, key: `phoenix_mars_lander`, category: `space_probes_mars`, url: `https://astro-dic.jp/phoenix-mars/`, url_en: ``},
{id: `0DDF3A7F`, jp: `マーズエキスプレス探査機`, en: `Mars Express`, key: `mars_express`, category: `space_probes_mars`, url: `https://astro-dic.jp/mars-express/`, url_en: ``},
{id: `0F0D05AF`, jp: `マーズエクスプロレーションローバー計画`, en: `Mars Exploration Rover Mission`, key: `mars_exploration_rover_mission`, category: `space_probes_mars`, url: `https://astro-dic.jp/mars-exploration-rover-mission/`, url_en: ``},
{id: `0EE29592`, jp: `マーズグローバルサーベイヤー探査機`, en: `Mars Global Surveyor`, key: `mars_global_surveyor`, category: `space_probes_mars`, url: `https://astro-dic.jp/mars-global-surveyor/`, url_en: ``},
{id: `88D530D2`, jp: `マーズパスファインダー探査機`, en: `Mars Pathfinder`, key: `mars_pathfinder`, category: `space_probes_mars`, url: `https://astro-dic.jp/mars-pathfinder/`, url_en: ``},
{id: `8832361F`, jp: `マゼラン探査機`, en: `Magellan Spacecraft`, key: `magellan_spacecraft`, category: `space_probes_venus`, url: `https://astro-dic.jp/magellan/`, url_en: ``},
{id: `FF28D7E5`, jp: `パイオニアビーナス探査機`, en: `Pioneer Venus`, key: `pioneer_venus`, category: `space_probes_venus`, url: `https://astro-dic.jp/pioneer-venus/`, url_en: ``},
{id: `B31CC545`, jp: `ビーナス・エクスプレス`, en: `Venus Express`, key: `venus_express`, category: `space_probes_venus`, url: `https://ja.wikipedia.org/wiki/%E3%83%93%E3%83%BC%E3%83%8A%E3%82%B9%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%97%E3%83%AC%E3%82%B9`, url_en: `https://en.wikipedia.org/wiki/Venus_Express`},
{id: `7A181573`, jp: `メッセンジャー`, en: `MESSENGER`, key: `messenger`, category: `space_probes_mercury`, url: `https://ja.wikipedia.org/wiki/%E3%83%A1%E3%83%83%E3%82%BB%E3%83%B3%E3%82%B8%E3%83%A3%E3%83%BC_(%E6%8E%A2%E6%9F%BB%E6%A9%9F)`, url_en: `https://en.wikipedia.org/wiki/MESSENGER`},
{id: `AE7B0118`, jp: `マリナー10号`, en: `Mariner 10`, key: `mariner_10`, category: `space_probes_mercury`, url: `https://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%AA%E3%83%8A%E3%83%BC10%E5%8F%B7`, url_en: `https://en.wikipedia.org/wiki/Mariner_10`},
{id: `770D9FC3`, jp: `ベピ・コロンボ`, en: `BepiColombo`, key: `bepicolombo`, category: `space_probes_mercury`, url: `https://www.isas.jaxa.jp/missions/spacecraft/current/mmo.html`, url_en: `https://en.wikipedia.org/wiki/BepiColombo`},
{id: `551EA0F9`, jp: `ニアー探査機`, en: `NEAR Shoemaker`, key: `near_shoemaker`, category: `space_probes_near_earth`, url: `https://astro-dic.jp/near/`, url_en: ``},
{id: `E8D25925`, jp: `はやぶさ探査機`, en: `Hayabusa`, key: `hayabusa`, category: `space_probes_near_earth`, url: `https://astro-dic.jp/hayabusa-spacecraft/`, url_en: ``},
{id: `A6601B3E`, jp: `はやぶさ２探査機`, en: `Hayabusa-2`, key: `hayabusa-2`, category: `space_probes_near_earth`, url: `https://astro-dic.jp/hayabusa2-spacecraft/`, url_en: ``},
{id: `52DE1C02`, jp: `スターダスト探査機`, en: `Stardust Spacecraft`, key: `stardust_spacecraft`, category: `space_probes_commet`, url: `https://astro-dic.jp/stardust/`, url_en: ``},
{id: `1DD3DA72`, jp: `ジオット彗星探査機`, en: `Giotto`, key: `giotto`, category: `space_probes_commet`, url: `https://astro-dic.jp/giotto/`, url_en: ``},
{id: `FE427F5E`, jp: `ユリシーズ探査機`, en: `Ulysses Spacecraft`, key: `ulysses_spacecraft`, category: `space_probes_sun`, url: `https://astro-dic.jp/ulysses/`, url_en: ``},
{id: `C6A4B8B5`, jp: `パーカー・ソーラー・プローブ`, en: `Parker Solar Probe`, key: `parker_solar_probe`, category: `space_probes_sun`, url: `https://ja.wikipedia.org/wiki/%E3%83%91%E3%83%BC%E3%82%AB%E3%83%BC%E3%83%BB%E3%82%BD%E3%83%BC%E3%83%A9%E3%83%BC%E3%83%BB%E3%83%97%E3%83%AD%E3%83%BC%E3%83%96`, url_en: `https://en.wikipedia.org/wiki/Parker_Solar_Probe`},
{id: `92137DAC`, jp: `クレメンタイン探査機`, en: `Clementine`, key: `clementine`, category: `space_probes_moon`, url: `https://astro-dic.jp/clementine/`, url_en: ``},
{id: `C09AD267`, jp: `かぐや探査機`, en: `KAGUYA`, key: `kaguya`, category: `space_probes_moon`, url: `https://astro-dic.jp/kaguya/`, url_en: ``},
{id: `7EFD3A24`, jp: `ボイジャー探査機`, en: `Voyager`, key: `voyager`, category: `trans_neptunian`, url: `https://astro-dic.jp/voyager/`, url_en: ``},
{id: `5DB3091F`, jp: `ニューホライズンズ探査機`, en: `New Horizons`, key: `new_horizons`, category: `dwarf_planet`, url: `https://astro-dic.jp/new-horizons/`, url_en: ``},
{id: `9CF553BE`, jp: `カッシーニ探査機`, en: `Cassini`, key: `cassini`, category: `saturn`, url: `https://astro-dic.jp/cassini/`, url_en: ``},
{id: `989CC56A`, jp: `ガリレオ探査機`, en: `Galileo Spacecraft`, key: `galileo_spacecraft`, category: `jupiter`, url: `https://astro-dic.jp/galileo/`, url_en: ``},
{id: `B5E97BB3`, jp: `オポチュニティ (探査機)`, en: `Mars Rover Opportunity`, key: `mars_rover_opportunity`, category: `mars`, url: `https://astro-dic.jp/opportunity/`, url_en: ``},
{id: `DBB8CEB7`, jp: `キュリオシティ (探査機)`, en: `Mars Rover Curiosity`, key: `mars_rover_curiosity`, category: `mars`, url: `https://astro-dic.jp/curiosity/`, url_en: ``},
{id: `18344468`, jp: `スピリット (探査機)`, en: `Mars Rover Spirit`, key: `mars_rover_spirit`, category: `mars`, url: `https://astro-dic.jp/spirit/`, url_en: ``},
{id: `6E8D4BDA`, jp: `パーサビアランス (探査機)`, en: `Mars Rover Perseverance`, key: `mars_rover_perseverance`, category: `mars`, url: `https://astro-dic.jp/perseverance/`, url_en: ``},
{id: `7ABC59B4`, jp: `バイキング探査機`, en: `Viking`, key: `viking`, category: `mars`, url: `https://astro-dic.jp/viking/`, url_en: ``},
{id: `425042C2`, jp: `フェニックス探査機`, en: `Phoenix Mars Lander`, key: `phoenix_mars_lander`, category: `mars`, url: `https://astro-dic.jp/phoenix-mars/`, url_en: ``},
{id: `BA319940`, jp: `マーズエキスプレス探査機`, en: `Mars Express`, key: `mars_express`, category: `mars`, url: `https://astro-dic.jp/mars-express/`, url_en: ``},
{id: `AE6B26C6`, jp: `マーズエクスプロレーションローバー計画`, en: `Mars Exploration Rover Mission`, key: `mars_exploration_rover_mission`, category: `mars`, url: `https://astro-dic.jp/mars-exploration-rover-mission/`, url_en: ``},
{id: `361EBF47`, jp: `マーズグローバルサーベイヤー探査機`, en: `Mars Global Surveyor`, key: `mars_global_surveyor`, category: `mars`, url: `https://astro-dic.jp/mars-global-surveyor/`, url_en: ``},
{id: `40EF4E9E`, jp: `マーズパスファインダー探査機`, en: `Mars Pathfinder`, key: `mars_pathfinder`, category: `mars`, url: `https://astro-dic.jp/mars-pathfinder/`, url_en: ``},
{id: `BCBD98B9`, jp: `マゼラン探査機`, en: `Magellan Spacecraft`, key: `magellan_spacecraft`, category: `venus`, url: `https://astro-dic.jp/magellan/`, url_en: ``},
{id: `6E1C60BA`, jp: `パイオニアビーナス探査機`, en: `Pioneer Venus`, key: `pioneer_venus`, category: `venus`, url: `https://astro-dic.jp/pioneer-venus/`, url_en: ``},
{id: `20E6F082`, jp: `ビーナス・エクスプレス (探査機)`, en: `Venus Express`, key: `venus_express`, category: `venus`, url: `https://ja.wikipedia.org/wiki/%E3%83%93%E3%83%BC%E3%83%8A%E3%82%B9%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%97%E3%83%AC%E3%82%B9`, url_en: `https://en.wikipedia.org/wiki/Venus_Express`},
{id: `52971019`, jp: `メッセンジャー (探査機)`, en: `MESSENGER`, key: `messenger`, category: `mercury`, url: `https://ja.wikipedia.org/wiki/%E3%83%A1%E3%83%83%E3%82%BB%E3%83%B3%E3%82%B8%E3%83%A3%E3%83%BC_(%E6%8E%A2%E6%9F%BB%E6%A9%9F)`, url_en: `https://en.wikipedia.org/wiki/MESSENGER`},
{id: `5556AFAC`, jp: `マリナー10号 (探査機)`, en: `Mariner 10`, key: `mariner_10`, category: `mercury`, url: `https://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%AA%E3%83%8A%E3%83%BC10%E5%8F%B7`, url_en: `https://en.wikipedia.org/wiki/Mariner_10`},
{id: `26FFB8DC`, jp: `ベピ・コロンボ (探査機)`, en: `BepiColombo`, key: `bepicolombo`, category: `mercury`, url: `https://www.isas.jaxa.jp/missions/spacecraft/current/mmo.html`, url_en: `https://en.wikipedia.org/wiki/BepiColombo`},
{id: `7F0FDB40`, jp: `ニアー探査機`, en: `NEAR Shoemaker`, key: `near_shoemaker`, category: `asteroids`, url: `https://astro-dic.jp/near/`, url_en: ``},
{id: `867DB120`, jp: `はやぶさ探査機`, en: `Hayabusa`, key: `hayabusa`, category: `asteroids`, url: `https://astro-dic.jp/hayabusa-spacecraft/`, url_en: ``},
{id: `15336E0C`, jp: `はやぶさ２探査機`, en: `Hayabusa-2`, key: `hayabusa-2`, category: `asteroids`, url: `https://astro-dic.jp/hayabusa2-spacecraft/`, url_en: ``},
{id: `6DCD64E8`, jp: `スターダスト探査機`, en: `Stardust Spacecraft`, key: `stardust_spacecraft`, category: `comet`, url: `https://astro-dic.jp/stardust/`, url_en: ``},
{id: `42583B29`, jp: `ジオット彗星探査機`, en: `Giotto`, key: `giotto`, category: `comet`, url: `https://astro-dic.jp/giotto/`, url_en: ``},
{id: `5AAC8E2E`, jp: `ユリシーズ探査機`, en: `Ulysses Spacecraft`, key: `ulysses_spacecraft`, category: `sun`, url: `https://astro-dic.jp/ulysses/`, url_en: ``},
{id: `31A14FCB`, jp: `パーカー・ソーラー・プローブ (探査機)`, en: `Parker Solar Probe`, key: `parker_solar_probe`, category: `sun`, url: `https://ja.wikipedia.org/wiki/%E3%83%91%E3%83%BC%E3%82%AB%E3%83%BC%E3%83%BB%E3%82%BD%E3%83%BC%E3%83%A9%E3%83%BC%E3%83%BB%E3%83%97%E3%83%AD%E3%83%BC%E3%83%96`, url_en: `https://en.wikipedia.org/wiki/Parker_Solar_Probe`},
{id: `45611DF4`, jp: `クレメンタイン探査機`, en: `Clementine`, key: `clementine`, category: `moon_earth`, url: `https://astro-dic.jp/clementine/`, url_en: ``},
{id: `53B38B04`, jp: `かぐや探査機`, en: `KAGUYA`, key: `kaguya`, category: `moon_earth`, url: `https://astro-dic.jp/kaguya/`, url_en: ``},
{id: `34CCABDF`, jp: `スペースX`, en: `SpaceX`, key: `spacex`, category: `spacecraft_makers`, url: `https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9X`, url_en: ``},
{id: `7C825825`, jp: `イーロン・マスク`, en: `Elon Musk`, key: `elon_musk`, category: `spacecraft_makers`, url: `https://ja.wikipedia.org/wiki/%E3%82%A4%E3%83%BC%E3%83%AD%E3%83%B3%E3%83%BB%E3%83%9E%E3%82%B9%E3%82%AF`, url_en: ``},
{id: `E2477E4E`, jp: `アライアント・テックシステムズ`, en: `Alliant Techsystems`, key: `alliant_techsystems`, category: `spacecraft_makers`, url: `https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%83%BB%E3%83%86%E3%83%83%E3%82%AF%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%82%BA`, url_en: ``},
{id: `BDF6C8A0`, jp: `オービタル・サイエンシズ`, en: `Orbital Sciences Corporation`, key: `orbital_sciences_corporation`, category: `spacecraft_makers`, url: `https://ja.wikipedia.org/wiki/%E3%82%AA%E3%83%BC%E3%83%93%E3%82%BF%E3%83%AB%E3%83%BB%E3%82%B5%E3%82%A4%E3%82%A8%E3%83%B3%E3%82%B7%E3%82%BA`, url_en: ``},
{id: `929B7F15`, jp: `ノースロップ・グラマン・イノベーション・システムズ`, en: `Northrop Grumman Innovation Systems`, key: `northrop_grumman_innovation_systems`, category: `spacecraft_makers`, url: `https://ja.wikipedia.org/wiki/%E3%83%8E%E3%83%BC%E3%82%B9%E3%83%AD%E3%83%83%E3%83%97%E3%83%BB%E3%82%B0%E3%83%A9%E3%83%9E%E3%83%B3%E3%83%BB%E3%82%A4%E3%83%8E%E3%83%99%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%BB%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%82%BA`, url_en: ``},
{id: `43F37AD6`, jp: `シエラ・ネヴァダ・コーポレーション`, en: `Sierra Nevada Corporation`, key: `sierra_nevada_corporation`, category: `spacecraft_makers`, url: `https://ja.wikipedia.org/wiki/%E3%82%B7%E3%82%A8%E3%83%A9%E3%83%BB%E3%83%8D%E3%83%B4%E3%82%A1%E3%83%80%E3%83%BB%E3%82%B3%E3%83%BC%E3%83%9D%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3`, url_en: ``},
{id: `D628B245`, jp: `ブルーオリジン`, en: `Blue Origin`, key: `blue_origin`, category: `spacecraft_makers`, url: `https://ja.wikipedia.org/wiki/%E3%83%96%E3%83%AB%E3%83%BC%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%B3`, url_en: ``},
{id: `176B0582`, jp: `ボーイング`, en: `Boeing`, key: `boeing`, category: `spacecraft_makers`, url: `https://ja.wikipedia.org/wiki/%E3%83%9C%E3%83%BC%E3%82%A4%E3%83%B3%E3%82%B0`, url_en: ``},
{id: `00C2023D`, jp: `Dragon Spacecraft`, en: `Dragon Spacecraft`, key: `dragon_spacecraft`, category: `spacecraft_spacex`, url: `https://www.spacex.com/vehicles/dragon/`, url_en: ``},
{id: `6765D8C5`, jp: `Falcon 9`, en: `Falcon 9`, key: `falcon_9`, category: `spacecraft_spacex`, url: `https://www.spacex.com/vehicles/falcon-9/`, url_en: ``},
{id: `A36A742A`, jp: `Falcon Heavy`, en: `Falcon Heavy`, key: `falcon_heavy`, category: `spacecraft_spacex`, url: `https://www.spacex.com/vehicles/falcon-heavy/`, url_en: ``},
{id: `D32FCB9E`, jp: `Cygnus Spacecraft`, en: `Cygnus Spacecraft`, key: `cygnus_spacecraft`, category: `spacecraft_others`, url: ``, url_en: ``},
{id: `44081B5C`, jp: `Dream Chaser`, en: `Dream Chaser`, key: `dream_chaser`, category: `spacecraft_others`, url: ``, url_en: ``},
{id: `AFB4C8BC`, jp: `CST-100`, en: `CST-100`, key: `cst-100`, category: `spacecraft_others`, url: ``, url_en: ``},
{id: `AAA35BD8`, jp: `商業補給サービス`, en: `Commercial Resupply Service`, key: `commercial_resupply_service`, category: `commercial_resupply_spacex`, url: ``, url_en: ``},
{id: `96974D40`, jp: `SpaceX CRS-1`, en: `SpaceX CRS-1`, key: `spacex_crs-1`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-1`, url_en: ``},
{id: `E61E542D`, jp: `SpaceX CRS-2`, en: `SpaceX CRS-2`, key: `spacex_crs-2`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-2`, url_en: ``},
{id: `DF02B1D3`, jp: `SpaceX CRS-3`, en: `SpaceX CRS-3`, key: `spacex_crs-3`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-3`, url_en: ``},
{id: `3CB97DC6`, jp: `SpaceX CRS-4`, en: `SpaceX CRS-4`, key: `spacex_crs-4`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-4`, url_en: ``},
{id: `49E66A10`, jp: `SpaceX CRS-5`, en: `SpaceX CRS-5`, key: `spacex_crs-5`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-5`, url_en: ``},
{id: `8477DF37`, jp: `SpaceX CRS-6`, en: `SpaceX CRS-6`, key: `spacex_crs-6`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-6`, url_en: ``},
{id: `FC66B80C`, jp: `SpaceX CRS-7`, en: `SpaceX CRS-7`, key: `spacex_crs-7`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-7`, url_en: ``},
{id: `5DC65931`, jp: `SpaceX CRS-8`, en: `SpaceX CRS-8`, key: `spacex_crs-8`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-8`, url_en: ``},
{id: `5F227FD3`, jp: `SpaceX CRS-9`, en: `SpaceX CRS-9`, key: `spacex_crs-9`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-9`, url_en: ``},
{id: `D4EEEF2A`, jp: `SpaceX CRS-10`, en: `SpaceX CRS-10`, key: `spacex_crs-10`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-10`, url_en: ``},
{id: `16B53411`, jp: `SpaceX CRS-11`, en: `SpaceX CRS-11`, key: `spacex_crs-11`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-11`, url_en: ``},
{id: `6E1A157C`, jp: `SpaceX CRS-12`, en: `SpaceX CRS-12`, key: `spacex_crs-12`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-12`, url_en: ``},
{id: `B4D70D69`, jp: `SpaceX CRS-13`, en: `SpaceX CRS-13`, key: `spacex_crs-13`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-13`, url_en: ``},
{id: `512D5CFF`, jp: `SpaceX CRS-14`, en: `SpaceX CRS-14`, key: `spacex_crs-14`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-14`, url_en: ``},
{id: `18ECFFC6`, jp: `SpaceX CRS-15`, en: `SpaceX CRS-15`, key: `spacex_crs-15`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-15`, url_en: ``},
{id: `7FF811C0`, jp: `SpaceX CRS-16`, en: `SpaceX CRS-16`, key: `spacex_crs-16`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-16`, url_en: ``},
{id: `8DFD2590`, jp: `SpaceX CRS-17`, en: `SpaceX CRS-17`, key: `spacex_crs-17`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-17`, url_en: ``},
{id: `DF139E10`, jp: `SpaceX CRS-18`, en: `SpaceX CRS-18`, key: `spacex_crs-18`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-18`, url_en: ``},
{id: `52138F8E`, jp: `SpaceX CRS-19`, en: `SpaceX CRS-19`, key: `spacex_crs-19`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-19`, url_en: ``},
{id: `99E6C4D5`, jp: `SpaceX CRS-20`, en: `SpaceX CRS-20`, key: `spacex_crs-20`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-20`, url_en: ``},
{id: `536EB1B3`, jp: `SpaceX CRS-21`, en: `SpaceX CRS-21`, key: `spacex_crs-21`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-21`, url_en: ``},
{id: `99980C23`, jp: `SpaceX CRS-22`, en: `SpaceX CRS-22`, key: `spacex_crs-22`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-22`, url_en: ``},
{id: `0189DD99`, jp: `SpaceX CRS-23`, en: `SpaceX CRS-23`, key: `spacex_crs-23`, category: `commercial_resupply_spacex`, url: `https://en.wikipedia.org/wiki/SpaceX_CRS-23`, url_en: ``},
{id: `86ACE7CB`, jp: `Cygnus CRS-1`, en: `Cygnus CRS-1`, key: `cygnus_crs-1`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_Orb-1`, url_en: ``},
{id: `368F82F7`, jp: `Cygnus CRS-2`, en: `Cygnus CRS-2`, key: `cygnus_crs-2`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_Orb-2`, url_en: ``},
{id: `12D87956`, jp: `Cygnus CRS-3`, en: `Cygnus CRS-3`, key: `cygnus_crs-3`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_Orb-3`, url_en: ``},
{id: `90242385`, jp: `Cygnus CRS-4`, en: `Cygnus CRS-4`, key: `cygnus_crs-4`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_OA-4`, url_en: ``},
{id: `1D55F87D`, jp: `Cygnus CRS-5`, en: `Cygnus CRS-5`, key: `cygnus_crs-5`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_OA-5`, url_en: ``},
{id: `5816366C`, jp: `Cygnus CRS-6`, en: `Cygnus CRS-6`, key: `cygnus_crs-6`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_OA-6`, url_en: ``},
{id: `05581902`, jp: `Cygnus CRS-7`, en: `Cygnus CRS-7`, key: `cygnus_crs-7`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_OA-7`, url_en: ``},
{id: `1D8E666D`, jp: `Cygnus CRS-8`, en: `Cygnus CRS-8`, key: `cygnus_crs-8`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_OA-8E`, url_en: ``},
{id: `1CD80508`, jp: `Cygnus CRS-9`, en: `Cygnus CRS-9`, key: `cygnus_crs-9`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_OA-9E`, url_en: ``},
{id: `C91EE6C6`, jp: `Cygnus CRS-10`, en: `Cygnus CRS-10`, key: `cygnus_crs-10`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-10`, url_en: ``},
{id: `6FA3B5DD`, jp: `Cygnus CRS-11`, en: `Cygnus CRS-11`, key: `cygnus_crs-11`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-11`, url_en: ``},
{id: `B0C7CEE5`, jp: `Cygnus CRS-12`, en: `Cygnus CRS-12`, key: `cygnus_crs-12`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-12`, url_en: ``},
{id: `D034CCFD`, jp: `Cygnus CRS-13`, en: `Cygnus CRS-13`, key: `cygnus_crs-13`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-13`, url_en: ``},
{id: `97F1AEDD`, jp: `Cygnus CRS-14`, en: `Cygnus CRS-14`, key: `cygnus_crs-14`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-14`, url_en: ``},
{id: `82D63663`, jp: `Cygnus CRS-15`, en: `Cygnus CRS-15`, key: `cygnus_crs-15`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-15`, url_en: ``},
{id: `A9BED62D`, jp: `Cygnus CRS-16`, en: `Cygnus CRS-16`, key: `cygnus_crs-16`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-16`, url_en: ``},
{id: `B1302D63`, jp: `Cygnus CRS-17`, en: `Cygnus CRS-17`, key: `cygnus_crs-17`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-17`, url_en: ``},
{id: `1D26FC16`, jp: `Cygnus CRS-18`, en: `Cygnus CRS-18`, key: `cygnus_crs-18`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-18`, url_en: ``},
{id: `A1B7765C`, jp: `Cygnus CRS-19`, en: `Cygnus CRS-19`, key: `cygnus_crs-19`, category: `commercial_resupply_others`, url: `https://en.wikipedia.org/wiki/Cygnus_NG-19`, url_en: ``},
]

export const category = [
{catName: `太陽`, value: `sun`, en:`Sun`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `水星`, value: `mercury`, en:`Mercury`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `金星`, value: `venus`, en:`Venus`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `地球`, value: `earth`, en:`Earth`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `火星`, value: `mars`, en:`Mars`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `木星`, value: `jupiter`, en:`Jupiter`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `土星`, value: `saturn`, en:`Saturn`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `天王星`, value: `uranus`, en:`Uranus`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `海王星`, value: `neptune`, en:`Neptune`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `惑星`, value: `planets`, en:`Planets`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `月`, value: `moon_earth`, en:`Moon`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `衛星`, value: `moons`, en:`Moons`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `準惑星`, value: `dwarf_planet`, en:`Dwarf Planet`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `小惑星`, value: `asteroids`, en:`Asteroids`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `彗星`, value: `comet`, en:`Comet`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `流星`, value: `meteor`, en:`Meteor`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `隕石`, value: `meteorite`, en:`Meteorite`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `太陽系外縁天体`, value: `trans_neptunian`, en:`Trans Neptunian`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `太陽系その他`, value: `solar_system`, en:`Solar System Otehrs`, parent_value: `solar_system`, parent_jp: `太陽系`, parent_en: `Solar System`},
{catName: `天の川`, value: `milky_way`, en:`Milky Way`, parent_value: `local_group`, parent_jp: `局所銀河群`, parent_en: `Local Group`},
{catName: `局所銀河群`, value: `local_group`, en:`Local Group`, parent_value: `local_group`, parent_jp: `局所銀河群`, parent_en: `Local Group`},
{catName: `恒星`, value: `stars`, en:`Stars`, parent_value: `stars`, parent_jp: `恒星`, parent_en: `Stars`},
{catName: `変光星`, value: `variable_star`, en:`Variable Star`, parent_value: `stars`, parent_jp: `恒星`, parent_en: `Stars`},
{catName: `超新星`, value: `supernova`, en:`Supernova`, parent_value: `stars`, parent_jp: `恒星`, parent_en: `Stars`},
{catName: `星形成`, value: `star_formation`, en:`Star Formation`, parent_value: `stars`, parent_jp: `恒星`, parent_en: `Stars`},
{catName: `星団`, value: `star_cluster`, en:`Star Cluster`, parent_value: `stars`, parent_jp: `恒星`, parent_en: `Stars`},
{catName: `星雲`, value: `nebula`, en:`Nebula`, parent_value: `intersteller_matter`, parent_jp: `星間物質`, parent_en: `Intersteller Matter`},
{catName: `星間物質`, value: `Interstellar matter`, en:`Interstellar Matter`, parent_value: `intersteller_matter`, parent_jp: `星間物質`, parent_en: `Intersteller Matter`},
{catName: `銀河`, value: `galaxies`, en:`Galaxies`, parent_value: `galaxy`, parent_jp: `銀河`, parent_en: `Galaxy`},
{catName: `銀河 (カテゴリー)`, value: `galaxy_category`, en:`Galaxy (Category)`, parent_value: `galaxy`, parent_jp: `銀河`, parent_en: `Galaxy`},
{catName: `活動銀河`, value: `active_galaxy`, en:`Active Galaxy`, parent_value: `galaxy`, parent_jp: `銀河`, parent_en: `Galaxy`},
{catName: `銀河団`, value: `galaxy_cluster`, en:`Galaxy Cluster`, parent_value: `galaxy`, parent_jp: `銀河`, parent_en: `Galaxy`},
{catName: `中性子星`, value: `neutron_star`, en:`Neutron Star`, parent_value: `high_energy_phenomena`, parent_jp: `高エネルギー現象`, parent_en: `High-Energy`},
{catName: `ブラックホール`, value: `black_hole`, en:`Black Hole`, parent_value: `high_energy_phenomena`, parent_jp: `高エネルギー現象`, parent_en: `High-Energy`},
{catName: `宇宙線`, value: `cosmic_rays`, en:`Cosmic Rays`, parent_value: `high_energy_phenomena`, parent_jp: `高エネルギー現象`, parent_en: `High-Energy`},
{catName: `超新星残骸`, value: `supernova_remnant`, en:`Spernova Remnant`, parent_value: `high_energy_phenomena`, parent_jp: `高エネルギー現象`, parent_en: `High-Energy`},
{catName: `地上望遠鏡`, value: `ground_telescopes`, en:`Ground Telescopes`, parent_value: `telescopes`, parent_jp: `望遠鏡`, parent_en: `Telescopes`},
{catName: `宇宙望遠鏡`, value: `space_telescopes`, en:`Space Telescopes`, parent_value: `telescopes`, parent_jp: `望遠鏡`, parent_en: `Telescopes`},
{catName: `太陽極域`, value: `space_probes_sun`, en:`Solar Polar`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `月 (探査機)`, value: `space_probes_moon`, en:`Moon`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `水星 (探査機)`, value: `space_probes_mercury`, en:`Mercury`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `金星 (探査機)`, value: `space_probes_venus`, en:`Venus`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `火星 (探査機)`, value: `space_probes_mars`, en:`Mars`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `木星 (探査機)`, value: `space_probes_jupiter`, en:`Jupiter`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `土星 (探査機)`, value: `space_probes_saturn`, en:`Saturn`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `地球近傍小惑星 (探査機)`, value: `space_probes_near_earth`, en:`Near Earth Asteroid`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `彗星 (探査機)`, value: `space_probes_commet`, en:`Commet`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `冥王星 (探査機)`, value: `space_probes_pluto`, en:`Pluto`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `外惑星 (探査機)`, value: `space_probes_outer_planetary`, en:`Outer Planetary`, parent_value: `probes`, parent_jp: `探査機`, parent_en: `Probes`},
{catName: `宇宙船メーカー`, value: `spacecraft_makers`, en:`Spacecraft Makers`, parent_value: `spacecraft_makers`, parent_jp: `宇宙船メーカー`, parent_en: `Spacecraft Makers`},
{catName: `宇宙船(スペースX)`, value: `spacecraft_spacex`, en:`Spacecraft (SpaceX)`, parent_value: `spacecraft_makers`, parent_jp: `宇宙船メーカー`, parent_en: `Spacecraft Makers`},
{catName: `宇宙船(その他)`, value: `spacecraft_others`, en:`Spacecraft (Others)`, parent_value: `spacecraft_makers`, parent_jp: `宇宙船メーカー`, parent_en: `Spacecraft Makers`},
{catName: `商業補給サービス(スペースX)`, value: `commercial_resupply_spacex`, en:`Commercial Resupply Service (SpaceX)`, parent_value: `spacecraft_makers`, parent_jp: `宇宙船メーカー`, parent_en: `Spacecraft Makers`},
{catName: `商業補給サービス(その他)`, value: `commercial_resupply_others`, en:`Commercial Resupply Service (Others)`, parent_value: `spacecraft_makers`, parent_jp: `宇宙船メーカー`, parent_en: `Spacecraft Makers`},
            ]

 
export const categoryParents = category.map(item => ({
                                 parent_value:item.parent_value, 
                                 parent_jp:item.parent_jp,
                                 parent_en:item.parent_en
                                }))               
export const  categoryParentsValues = categoryParents.map(item => item.parent_value).filter(onlyUnique)        